language: ruby
rvm:
  - 2.4.1

branches:
  only:
  - gh-pages    
  - /pages-(.*)/

cache: bundler

before_script:
 - chmod +x ./script/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]


install:
  - gem install jekyll html-proofer
  - bundle update
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --external_only --url-ignore "http://github.com/pages/devmjun/devmjun.github.io/feed.xml"
  

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
sudo: false



