language: ruby
rvm:
  - 2.4.1

branches:
  only:
  - gh-pages    
  - /pages-(.*)/

script: true 
cache: bundler

install:
  - gem install jekyll html-proofer
  - bundle update
  - bundle install
  - bundle exec rake
  - bundle exec htmlproofer ./_site --only-4xx --external_only --url-ignore "http://github.com/pages/ShikherVerma/Shikherverma.github.io/feed.xml"
  - bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
sudo: false



