language: ruby
rvm:
  - 2.4.1

#!/usr/bin/env ruby
script: 
  - ./script/cibuild
  - jekyll build && htmlproofer ./_site

branches:
  only:
  - gh-pages    
  - /pages-(.*)/

cache: bundler

install:
  - gem install jekyll html-proofer
  - bundle update
  - bundle install
  - bundle exec htmlproofer ./_site
  - bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
sudo: false

exclude: [vendor]

