language: ruby
rvm:
  - 2.4.1

branches:
  only:
  - gh-pages
  - /pages-(.*)/

before_script: true 
 

script:
  - bundle install --clean --force
  - bundle exec jekyll build 
  - bundle exec htmlproofer ./_site --only-4xx --external_only --url-ignore "http://github.com/pages/devmjun/devmjun.github.io/feed.xml"


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

before_install:
  - gem update --system
  - gem install bundler
 
install:
  - gem install jekyll html-proofer
  
  
sudo: false

exclude: [vendor]
