language: ruby
rvm:
  - 2.4.1

branches:
  only:
  - gh-pages

before_script:
 - chmod +x ./script/cibuild/*.sh

script:
  - ./script/cibuild/
  - bundle install 
  - jekyll build && htmlproofer ./_site --only-4xx --external_only --url-ignore "http://github.com/pages/devmjun/devmjun.github.io/feed.xml"


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

install:
  - gem install jekyll html-proofer
  
  
sudo: false

exclude: [vendor]
