language: ruby
rvm:
  - 2.4.1

sudo: false
cache: bundler

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

branches:
  only:
  - gh-pages

script:
  - bundle update --force
  - bundle install --clean --force
  - bundle exec jekyll build 
  - bundle exec htmlproofer ./_site --only-4xx --external_only --url-ignore "http://github.com/pages/devmjun/devmjun.github.io/feed.xml"

exclude: [vendor]

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - gem install jekyll html-proofer

before_script: true 
 
before_install:
  - gem update --system
  - gem install bundler
 