language: ruby
rvm:
  - 2.2.2



script: true 

install:
  - bundle update
  - bundle install 
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --external_only --url-ignore "http://github.com/pages/devmjun/devmjun.github.io/feed.xml"
  
sudo: false
