language: ruby
rvm:
  - 2.4.1

#!/usr/bin/env ruby


before_script:
  - chmod +x ./script/cibuild


script: ./script/cibuild


branches:
  only:
  - gh-pages    
  - /pages-(.*)/

cache: bundler

install:
  - gem install jekyll html-proofer
  


script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
sudo: false

exclude: [vendor]

